//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/site_publisher/views/publishController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/site_publisher/views/publishController-th.js
// Module:    /paper_lantern/site_publisher/views/publishController-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A problem has occurred: [_1]":"A problem has occurred: [_1]","The form has returned [quant,_1,error,errors]":"The form has returned [quant,_1,error,errors]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
