//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts-uk.js
// Module:    /paper_lantern/js2/ssl/crts-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A key that does not use at least [numf,_1]-bit encryption does not provide adequate security.":"Ключ, який не використовує принаймні [numf,_1]-розрядне шифрування, не забезпечує відповідний рівень безпеки.","Choose a country.":"Виберіть країну.","City":"Місто","Company":"Компанія","Company Division":"Відділення компанії","Country":"Країна","Domain":"Домен","Email":"Електронна пошта","Please use an email format (for example: [asis,user@example.com]).":"Використовуйте формат електронної пошти (наприклад, [asis,user@example.com]).","State":"Стан","The company division must be no longer than [quant,_1,character,characters].":"Довжина імені відділення компанії не має перевищувати [quant,_1,символ,симв.].","The company name must be no longer than [quant,_1,character,characters].":"Довжина імені компанії не має перевищувати [quant,_1,символ,симв.].","The “[_1]” field cannot be left blank.":"The “[_1]” field cannot be left blank.","You can only enter valid domains.":"Ви можете вводити лише дійсні домени.","You do not control this domain.":"Ви не керуєте цим доменом.","[numf,_1] of the [numerate,_2,domain,domains] that you have entered [numerate,_1,is a domain,are domains] that you do not control.":"[numf,_1] [numerate,_2,домену,доменів], яке ви ввели, [numerate,_1,є доменом,є доменами], яким ви не керуєте."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
