//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts-ja.js
// Module:    /paper_lantern/js2/ssl/crts-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A key that does not use at least [numf,_1]-bit encryption does not provide adequate security.":"[numf,_1] ビット以上の暗号化が使用されていないキーは、十分な安全性を確保できません。","Choose a country.":"国を選択します。","City":"市区町村","Company":"会社","Company Division":"会社の部署","Country":"国","Domain":"ドメイン","Email":"電子メール","Please use an email format (for example: [asis,user@example.com]).":"電子メール フォーマットを使用してください (例: [asis,user@example.com]）。","State":"ステータス","The company division must be no longer than [quant,_1,character,characters].":"会社の部署は、[quant,_1,文字,文字]以下である必要があります。","The company name must be no longer than [quant,_1,character,characters].":"会社名は、[quant,_1,文字,文字]以下である必要があります。","The “[_1]” field cannot be left blank.":"The “[_1]” field cannot be left blank.","You can only enter valid domains.":"有効なドメインのみを入力できます。","You do not control this domain.":"このドメインは、管理しているドメインではありません。","[numf,_1] of the [numerate,_2,domain,domains] that you have entered [numerate,_1,is a domain,are domains] that you do not control.":"入力した[numerate,_2,ドメイン,ドメイン]のうち、[numf,_1] 個の[numerate,_1,ドメイン,ドメイン]は、管理しているドメインではありません。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
