//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts-fil.js
// Module:    /paper_lantern/js2/ssl/crts-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A key that does not use at least [numf,_1]-bit encryption does not provide adequate security.":"Hindi nagbibigay ng sapat na seguridad ang isang key na hindi gumagamit ng hindi bababa sa [numf,_1]-bit na pag-encrypt.","Choose a country.":"Pumili ng bansa.","City":"Lungsod","Company":"Kumpanya","Company Division":"Sangay ng Kumpanya","Country":"Bansa","Domain":"Domain","Email":"Email","Please use an email format (for example: [asis,user@example.com]).":"Mangyaring gumamit ng format na para sa email (halimbawa: [asis,user@example.com]).","State":"Katayuan","The company division must be no longer than [quant,_1,character,characters].":"Ang dibisyon ng kumpanya ay dapat na hindi mas mahaba sa [quant,_1,character,(na) character].","The company name must be no longer than [quant,_1,character,characters].":"Ang pangalan ng kumpanya ay dapat na hindi mas mahaba sa [quant,_1,character,(na) character].","The “[_1]” field cannot be left blank.":"The “[_1]” field cannot be left blank.","You can only enter valid domains.":"Maaari ka lang maglagay ng mga wastong domain.","You do not control this domain.":"Hindi mo kinokontrol ang domain na ito.","[numf,_1] of the [numerate,_2,domain,domains] that you have entered [numerate,_1,is a domain,are domains] that you do not control.":"[numf,_1] ng [numerate,_2,domain,(na) domain] na naglagay ka ng [numerate,_1,ay isang domain,ay mga domain] na hindi mo kinokontrol."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
