//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts-th.js
// Module:    /paper_lantern/js2/ssl/crts-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A key that does not use at least [numf,_1]-bit encryption does not provide adequate security.":"คีย์ที่ไม่ใช้การเข้ารหัสอย่างน้อย [numf,_1] บิต ไม่ให้ความปลอดภัยที่เพียงพอ","Choose a country.":"เลือกประเทศ","City":"เมือง","Company":"บริษัท","Company Division":"แผนกในบริษัท","Country":"ประเทศ","Domain":"โดเมน","Email":"อีเมล","Please use an email format (for example: [asis,user@example.com]).":"โปรดใช้รูปแบบอีเมล (ตัวอย่าง: [asis,user@example.com]).","State":"สถานะ","The company division must be no longer than [quant,_1,character,characters].":"แผนกในบริษัทต้องไม่ยาวเกินกว่า [quant,_1,อักขระ,อักขระ]","The company name must be no longer than [quant,_1,character,characters].":"ชื่อบริษัทต้องไม่ยาวเกินกว่า [quant,_1,อักขระ,อักขระ]","The “[_1]” field cannot be left blank.":"The “[_1]” field cannot be left blank.","You can only enter valid domains.":"คุณสามารถใส่ได้เฉพาะโดเมนที่ถูกต้องเท่านั้น","You do not control this domain.":"คุณไม่ได้ควบคุมโดเมนนี้","[numf,_1] of the [numerate,_2,domain,domains] that you have entered [numerate,_1,is a domain,are domains] that you do not control.":"[numf,_1] ของ [numerate,_2,โดเมน,โดเมน] ที่คุณได้ใส่ [numerate,_1,คือโดเมน,คือโดเมน] ซึ่งคุณไม่ได้ควบคุม"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
