//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/crts-ms.js
// Module:    /paper_lantern/js2/ssl/crts-ms
// Locale:    ms
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A key that does not use at least [numf,_1]-bit encryption does not provide adequate security.":"Kekunci yang tidak menggunakan sekurang-kurangnya penyulitan [numf,_1]bit tidak menyediakan keselamatan yang mencukupi.","Choose a country.":"Pilih negara.","City":"Bandar","Company":"Syarikat","Company Division":"Divisyen Syarikat","Country":"Negara","Domain":"Domain","Email":"E-mel","Please use an email format (for example: [asis,user@example.com]).":"Gunakan format e-mel (sebagai contoh: [asis,user@example.com]).","State":"Keadaan","The company division must be no longer than [quant,_1,character,characters].":"Divisyen syarikat tidak boleh lebih dari [quant,_1,aksara,aksara].","The company name must be no longer than [quant,_1,character,characters].":"Nama syarikat tidak boleh lebih dari [quant,_1,aksara,aksara].","The “[_1]” field cannot be left blank.":"The “[_1]” field cannot be left blank.","You can only enter valid domains.":"Anda hanya boleh memasukkan domain yang sah.","You do not control this domain.":"Anda tidak mengawal domain ini.","[numf,_1] of the [numerate,_2,domain,domains] that you have entered [numerate,_1,is a domain,are domains] that you do not control.":"[numf,_1] bagi [numerate,_2,domain,domain] yang anda telah masukkan [numerate,_1,ialah domain,ialah domain-domain] yang anda tidak kawal."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
