//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/csrs.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/csrs-nb.js
// Module:    /paper_lantern/js2/ssl/csrs-nb
// Locale:    nb
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Choose a country.":"Velg et land.","City":"By","Company":"Firma","Company Division":"Bedriftsavdeling","Country":"Land","Domains":"Domener","Email":"E-post","Make sure to use a valid email format. For example, [asis,user@domain.com].":"Sørg for at du bruker et gyldig e-postformat. For eksempel [asis,user@domain.com].","Passphrase":"Passfrase","State":"Tilstand","The certificate signing request passphrase can contain only alphanumeric characters.":"Passfrasen for forespørselen om sertifikatsignering kan bare inneholde alfanumeriske tegn.","The certificate signing request passphrase must be at least [quant,_1,character,characters] long.":"Passfrasen i forespørselen om sertifikatsignering må være minst [quant,_1,tegn,tegn] lang.","The company division must be no longer than [quant,_1,character,characters].":"Bedriftsavdelingen kan ikke bestå av mer enn [quant,_1,tegn,tegn].","The company name must be no longer than [quant,_1,character,characters].":"Bedriftsnavnet kan ikke bestå av mer enn [quant,_1,tegn,tegn].","The passphrase must be no longer than [quant,_1,character,characters].":"Passfrasen må ikke være lenger enn [quant,_1,tegn,tegn].","The “[_1]” field cannot be left blank.":"The “[_1]” field cannot be left blank.","This field contains characters that some certificate authorities may not accept. Contact your certificate authority to confirm that they accept these characters.":"Dette feltet inneholder tegn som noen sertifiseringsinstanser kanskje ikke godkjenner. Kontakt sertifiseringsinstanser for å bekrefte at de godtar disse tegnene.","You can only enter valid domains.":"Du kan bare angi gyldige domener.","You do not control this domain.":"Du styrer ikke dette domenet.","[numf,_1] of the [numerate,_2,domain,domains] that you have entered [numerate,_1,is a domain,are domains] that you do not control.":"[numf,_1] av [numerate,_2,domene,domener] du har angitt [numerate,_1,er et domene,er domener] som du ikke styrer."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
