//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/csrs.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/csrs-da.js
// Module:    /paper_lantern/js2/ssl/csrs-da
// Locale:    da
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Choose a country.":"Vælg et land.","City":"By","Company":"Virksomhed","Company Division":"Afdeling af virksomhed","Country":"Land","Domains":"Domæner","Email":"Mail","Make sure to use a valid email format. For example, [asis,user@domain.com].":"Sørg for at bruge et gyldigt mailformat. Eksempelvis [asis,user@domain.com].","Passphrase":"Adgangsudtryk","State":"Tilstand","The certificate signing request passphrase can contain only alphanumeric characters.":"Adgangsudtrykket til certifikatsigneringsanmodningen må kun indeholde alfanumeriske tegn.","The certificate signing request passphrase must be at least [quant,_1,character,characters] long.":"Adgangsudtrykket til signeringsanmodningen for certifikatet skal være [quant,_1,tegn,tegn] langt.","The company division must be no longer than [quant,_1,character,characters].":"Virksomhedsafdelingen må højst være på [quant,_1,tegn,tegn].","The company name must be no longer than [quant,_1,character,characters].":"Virksomhedsnavnet må højst være på [quant,_1,tegn,tegn].","The passphrase must be no longer than [quant,_1,character,characters].":"Adgangsudtrykket må højst være på [quant,_1,tegn,tegn].","The “[_1]” field cannot be left blank.":"The “[_1]” field cannot be left blank.","This field contains characters that some certificate authorities may not accept. Contact your certificate authority to confirm that they accept these characters.":"Dette felt indeholder tegn, som nogle nøglecentre muligvis ikke accepterer. Kontakt dit nøglecenter for at bekræfte, at det accepterer disse tegn.","You can only enter valid domains.":"Du kan kun angive gyldige domæner.","You do not control this domain.":"Du styrer ikke dette domæne.","[numf,_1] of the [numerate,_2,domain,domains] that you have entered [numerate,_1,is a domain,are domains] that you do not control.":"[numf,_1] af de [numerate,_2,domæne,domæner], du har angivet [numerate,_1,er et domæne,er domæner], som du ikke styrer."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
