//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-ko.js
// Module:    /paper_lantern/js2/ssl/install-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"작업","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"SSL 호스트 “[_1]”을(를) 삭제하시겠습니까? 이 작업은 실행 취소할 수 없습니다!","Certificate Expiration":"인증서 만료","Confirm SSL Host Delete":"SSL 호스트 삭제 확인","Deleting SSL host “[_1]” …":"SSL 호스트 “[_1]”을(를) 삭제하는 중…","Document Root":"문서 루트","Is Primary Website on IP Address?":"기본 웹 사이트가 IP 주소로 연결되어 있습니까?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"웹 [output,acronym,SNI,Server Name Indication]가 필요합니까?","Loading …":"로드하는 중 …","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"Windows XP™의 Microsoft® Internet Explorer™는 가장 널리 사용되는 웹 브라우저이지만 SNI를 지원하지 않습니다.","No":"아니요","Setting “[_1]” as the primary SSL host on “[_2]” …":"“[_1]”을(를) 기본 SSL 호스트로 “[_2]”에 설정 중…","The SSL host for “[_1]” has been removed.":"“[_1]”에 대한 SSL 호스트가 제거되었습니다.","Yes":"예","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong,참고:] 전용 IP 주소가 없습니다. 결과적으로 [output,abbr,SNI,(Server Name Indication)]를 지원하지 않는 웹 브라우저는 SSL 웹 사이트에 액세스할 경우 사용자에게 거짓 보안 경고를 보낼 수 있습니다.","“[_1]” is now the primary SSL host on “[_2]”.":"현재 “[_1]”은(는) “[_2]”의 기본 SSL 호스트입니다."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
