//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-fr.js
// Module:    /paper_lantern/js2/ssl/install-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"Actions","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"Voulez-vous vraiment supprimer l’hôte SSL « [_1] » ? Cette opération est irréversible !","Certificate Expiration":"Expiration du certificat","Confirm SSL Host Delete":"Confirmer la suppression de l’hôte SSL","Deleting SSL host “[_1]” …":"Suppression de l’hôte SSL « [_1] »…","Document Root":"Racine du document","Is Primary Website on IP Address?":"Le site Web principal se trouve-t-il sur l’adresse IP ?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"L’extension [output,acronym,SNI,Server Name Indication] est-elle requise ?","Loading …":"Chargement…","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"Microsoft® Internet Explorer™ sous Windows XP™est le navigateur Web le plus utilisé qui ne prend pas en charge SNI.","No":"Non","Setting “[_1]” as the primary SSL host on “[_2]” …":"Définition de « [_1] » comme hôte SSL principal sur « [_2] »…","The SSL host for “[_1]” has been removed.":"L’hôte SSL de « [_1] » a été supprimé.","Yes":"Oui","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong,Remarque :] vous ne possédez pas d’adresse IP dédiée. Les navigateurs Web qui ne prennent pas en charge [output,abbr,SNI,Server Name Indication] transmettront donc probablement des avertissements de sécurité erronés aux utilisateurs qui accèdent à vos sites Web SSL.","“[_1]” is now the primary SSL host on “[_2]”.":"« [_1] » est à présent l’hôte SSL principal sur « [_2] »."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
