//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-ja.js
// Module:    /paper_lantern/js2/ssl/install-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"アクション","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"SSL ホスト “[_1]” を削除しますか?この操作を元に戻すことはできません。","Certificate Expiration":"証明書の期限切れ","Confirm SSL Host Delete":"SSL ホストの削除の確認","Deleting SSL host “[_1]” …":"SSL ホスト “[_1]” を削除しています…","Document Root":"ドキュメント ルート","Is Primary Website on IP Address?":"IP アドレスのプライマリ Web サイトですか?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"Web [output,acronym,SNI,Server Name Indication] が必要ですか?","Loading …":"読み込んでいます…","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"Windows XP™ の Microsoft® Internet Explorer™ は、SNI がサポートされていない Web ブラウザーの中で最も広く使用されています。","No":"いいえ","Setting “[_1]” as the primary SSL host on “[_2]” …":"“[_1]” を “[_2]” 上のプライマリ SSL ホストとして設定しています…","The SSL host for “[_1]” has been removed.":"“[_1]” の SSL ホストが削除されました。","Yes":"はい","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong, 注記:] 専用 IP アドレスはありません。そのため、[output,abbr,SNI,Server Name Indication] がサポートされていない Web ブラウザーでは、ユーザーが SSL Web サイトにアクセスしたときに、誤ったセキュリティの警告がユーザーに表示されます。","“[_1]” is now the primary SSL host on “[_2]”.":"“[_1]” が “[_2]” 上のプライマリ SSL ホストになりました。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
