//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-zh_tw.js
// Module:    /paper_lantern/js2/ssl/install-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"動作","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"您確定要刪除 SSL 主機“[_1]”嗎? 此作業無法復原!","Certificate Expiration":"憑證到期","Confirm SSL Host Delete":"確認刪除 SSL 主機","Deleting SSL host “[_1]” …":"正在刪除 SSL 主機“[_1]”…","Document Root":"文件根目錄","Is Primary Website on IP Address?":"IP 位址上有主要網站嗎?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"是否需要 Web [output,acronym,SNI,伺服器名稱指示]?","Loading …":"正在載入…","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"在不支援 SNI 的網頁瀏覽器中，Windows XP™ 的 Microsoft® Internet Explorer™ 是使用最廣泛的網頁瀏覽器。","No":"否","Setting “[_1]” as the primary SSL host on “[_2]” …":"設定 “[_1]” 為 “[_2]” 上的主要 SSL 主機…","The SSL host for “[_1]” has been removed.":"已移除“[_1]”的 SSL 主機。","Yes":"是","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong,附註:] 您沒有固定 IP 位址。 因此，當您的使用者存取您所有的 SSL 網站時，不支援 [output,abbr,SNI,伺服器名稱指示] 的網頁瀏覽器可能會對他們提出錯誤的安全性警告。","“[_1]” is now the primary SSL host on “[_2]”.":"“[_1]”現在已是“[_2]”上的主要 SSL 主機。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
