//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-uk.js
// Module:    /paper_lantern/js2/ssl/install-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"Дії","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"Видалити хост із захистом SSL „[_1]”? Цю операцію не можна скасувати!","Certificate Expiration":"Термін дії сертифіката","Confirm SSL Host Delete":"Підтвердити видалення хоста із захистом SSL","Deleting SSL host “[_1]” …":"Видалення хоста із захистом SSL „[_1]”…","Document Root":"Кореневий каталог документів","Is Primary Website on IP Address?":"Чи є основний веб-сайт для IP-адреси?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"Ввести веб-адресу із захистом [output,acronym,SNI,Server Name Indication — вказівник імені сервера]?","Loading …":"Завантаження…","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"Microsoft® Internet Explorer™ у Windows XP™ є найуживанішим веб-браузером, який не підтримує SNI.","No":"Ні","Setting “[_1]” as the primary SSL host on “[_2]” …":"Налаштування „[_1]” як основного хоста із захистом SSL для „[_2]”…","The SSL host for “[_1]” has been removed.":"Хост із захистом SSL для „[_1]” видалено.","Yes":"Так","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong,Примітка.] У вас немає виділеної IP-адреси. Таким чином, браузери, які не підтримують функцію [output,abbr,SNI,Server Name Indication — вказівник імені сервера], вірогідно, відображуватимуть помилкові попередження служби безпеки, коли користувачі переходитимуть на будь-який ваш веб-сайт із захистом SSL.","“[_1]” is now the primary SSL host on “[_2]”.":"„[_1]” наразі є основним хостом із захистом SSL для „[_2]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
