//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-fil.js
// Module:    /paper_lantern/js2/ssl/install-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"Mga Pagkilos","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"Sigurado ka bang gusto mong tanggalin ang SSL host na “[_1]?” Hindi maa-undo ang pagpapatakbong ito!","Certificate Expiration":"Pag-expire ng Certificate","Confirm SSL Host Delete":"Kumpirmahin ang Pagtanggal sa SSL Host","Deleting SSL host “[_1]” …":"Tinatanggal ang SSL host na “[_1]” …","Document Root":"Root ng Dokumento","Is Primary Website on IP Address?":"Nasa IP Address ba ang Pangunahing Website?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"Kinakailangan ba ang Web [output,acronym,SNI,Server Name Indication]?","Loading …":"Naglo-load …","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"Ang Microsoft® Internet Explorer™ sa Windows XP™ ay ang pinakakaraniwang ginagamit na web browser na hindi sumusuporta sa SNI.","No":"Hindi","Setting “[_1]” as the primary SSL host on “[_2]” …":"Itinatakda ang “[_1]” bilang primary SSL host sa “[_2]” …","The SSL host for “[_1]” has been removed.":"Naalis ang SSL host para sa “[_1].”","Yes":"Oo","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong,Tandaan:] Wala kang nakalaang IP address. Bilang resulta, ang mga web browser na hindi sumusuporta sa [output,abbr,SNI,Server Name Indication] ay malamang na magbibigay ng mga hindi totoong babala sa seguridad sa iyong mga user kapag na-access nila ang alinman sa iyong mga SSL website.","“[_1]” is now the primary SSL host on “[_2]”.":"Ang “[_1]”na ngayon ang pangunahing SSL host sa “[_2].”"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
