//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-zh.js
// Module:    /paper_lantern/js2/ssl/install-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"操作","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"是否确定要删除 SSL 主机“[_1]”?  此操作不可撤消!","Certificate Expiration":"证书过期","Confirm SSL Host Delete":"确认 SSL 主机删除","Deleting SSL host “[_1]” …":"正在删除 SSL 主机“[_1]”…","Document Root":"文档根目录","Is Primary Website on IP Address?":"是否是 IP 地址上的主网站?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"是否需要“Web [output,acronym,SNI,服务器名称指示]”?","Loading …":"正在加载…","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"Windows XP™ 上的 Microsoft® Internet Explorer™ 是最广泛使用的不支持 SNI 的 Web 浏览器。","No":"否","Setting “[_1]” as the primary SSL host on “[_2]” …":"正在将“[_1]”设置为“[_2]”上的主 SSL 主机…","The SSL host for “[_1]” has been removed.":"“[_1]”的 SSL 主机已删除。","Yes":"是","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong,注意:] 您没有专用 IP 地址。 因此，当用户访问您的任何 SSL 网站时，不支持 [output,abbr,SNI,服务器名称指示] 的 Web 浏览器有可能向这些用户显示虚假的安全警告。","“[_1]” is now the primary SSL host on “[_2]”.":"“[_1]”现在是“[_2]”上的主 SSL 主机。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
