//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/install-fi.js
// Module:    /paper_lantern/js2/ssl/install-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Actions":"Toimet","Are you sure that you want to delete the SSL host “[_1]”? This operation cannot be undone!":"Haluatko varmasti poistaa SSL-palvelimen [_1]? Tätä toimintoa ei voi kumota.","Certificate Expiration":"Varmenteen vanhentuminen","Confirm SSL Host Delete":"Vahvista SSL-palvelimen poisto","Deleting SSL host “[_1]” …":"Poistetaan SSL-palvelinta [_1]…","Document Root":"Tiedoston päätaso","Is Primary Website on IP Address?":"Onko ensisijainen verkkosivusto IP-osoitteessa?","Is Web [output,acronym,SNI,Server Name Indication] Required?":"Onko verkon [output,acronym,SNI,Server Name Indication] tarpeen?","Loading …":"Ladataan…","Microsoft® Internet Explorer™ on Windows XP™ is the most widely used web browser that does not support SNI.":"Windows XP™ ‑käyttöjärjestelmässä toimiva Microsoft® Internet Explorer™ on laajimmin käytetty SNI-tekniikkaa tukematon selain.","No":"Ei","Setting “[_1]” as the primary SSL host on “[_2]” …":"Asetetaan [_1] kohteen [_2] ensisijaiseksi SSL-palvelimeksi…","The SSL host for “[_1]” has been removed.":"Kohteen [_1] SSL-palvelin on poistettu.","Yes":"Kyllä","[output,abbr,FQDN,Fully Qualified Domain Name]s":"[output,abbr,FQDN,Fully Qualified Domain Name]s","[output,strong,Note:] You do not have a dedicated IP address. As a result, web browsers that do not support [output,abbr,SNI,Server Name Indication] will probably give false security warnings to your users when they access any of your SSL websites.":"[output,strong,Huomautus:] Sinulla ei ole kiinteää IP-osoitetta. Siksi selaimet, jotka eivät tue [output,abbr,SNI,Server Name Indication]-tekniikkaa, antavat todennäköisesti virheellisiä suojausvaroituksia käyttäjille, kun he käyttävät SSL-suojattua verkkosivustoasi.","“[_1]” is now the primary SSL host on “[_2]”.":"[_1] on nyt kohteen [_2] ensisijainen SSL-palvelin."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
