//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/keys.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ssl/keys-ru.js
// Module:    /paper_lantern/js2/ssl/keys-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A key that does not use at least [numf,_1]-bit encryption does not provide adequate security.":"Ключ, не использующий по крайней мере [numf,_1]-битное шифрование, не предоставляет надлежащую безопасность."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
