//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb-vi.js
// Module:    /paper_lantern/mail/lists/lists.cmb-vi
// Locale:    vi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"Truy cập","Admin":"Admin","Edit Privacy Options: “[_1]”":"Sửa Tùy Chọn Bảo Mật: “[_1]”","Functions":"Chức năng","List Name":"Tên Danh Sách","Saving …":"Đang lưu …","Usage":"Mức Dùng","[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1] … và [numf,_3] khác"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
