//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb-ko.js
// Module:    /paper_lantern/mail/lists/lists.cmb-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"액세스","Admin":"관리자","Edit Privacy Options: “[_1]”":"개인정보 옵션 편집: “[_1]”","Functions":"기능","List Name":"목록 이름","Saving …":"저장 중 …","Usage":"사용량","[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1] … 및 [numf,_3] 등"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
