//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService-fr.js
// Module:    /paper_lantern/user_manager/services/userService-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Email":"E-mail","FTP":"FTP","Hypothetical Subaccount":"Sous-compte hypothétique","Invite Expired":"Invite Expired","Invite Pending":"Invite Pending","Service Account":"Compte de service","Subaccount":"Sous-compte","The system could not delete the “[_1]” account. You cannot delete the “[_2]” account type.":"Le système n’a pas pu supprimer le compte « [_1] ». Vous ne pouvez pas supprimer le type de compte « [_2] ».","The system could not determine the service type for the “[_1]” service account.":"Le système n’a pas pu déterminer le type de service du compte de service « [_1] ».","The system detected an unknown service for the “[_1]” service account.":"Le système a détecté un service inconnu pour le compte de service « [_1] ».","The system failed to determine whether the username is available: [_1]":"Le système n’a pas pu déterminer si le nom d’utilisateur est disponible : [_1].","The username is not available.":"Le nom d’utilisateur n’est pas disponible.","This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.":"This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.","This user has not used the invitation to set a password.":"This user has not used the invitation to set a password.","Web Disk":"Web Disk","cPanel Account":"Compte cPanel"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
