//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService-nl.js
// Module:    /paper_lantern/user_manager/services/userService-nl
// Locale:    nl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Email":"E-mail","FTP":"FTP","Hypothetical Subaccount":"Hypothetische subaccount","Invite Expired":"Invite Expired","Invite Pending":"Invite Pending","Service Account":"Serviceaccount","Subaccount":"Subaccount","The system could not delete the “[_1]” account. You cannot delete the “[_2]” account type.":"De account ’[_1]’ kan niet worden verwijderd. U kunt het accounttype ’[_2]’ niet verwijderen.","The system could not determine the service type for the “[_1]” service account.":"Kan het servicetype niet bepalen voor de serviceaccount ’[_1]’.","The system detected an unknown service for the “[_1]” service account.":"Er is een onbekende service vastgesteld voor de serviceaccount ’[_1]’.","The system failed to determine whether the username is available: [_1]":"Kan niet bepalen of de gebruikersnaam beschikbaar is: [_1]","The username is not available.":"De gebruikersnaam is niet beschikbaar.","This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.":"This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.","This user has not used the invitation to set a password.":"This user has not used the invitation to set a password.","Web Disk":"Web Disk","cPanel Account":"cPanel-account"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
