//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService-ar.js
// Module:    /paper_lantern/user_manager/services/userService-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Email":"البريد الإلكتروني","FTP":"FTP","Hypothetical Subaccount":"حساب Hypothetical الفرعي","Invite Expired":"Invite Expired","Invite Pending":"Invite Pending","Service Account":"حساب الخدمة","Subaccount":"حساب فرعي","The system could not delete the “[_1]” account. You cannot delete the “[_2]” account type.":"يتعذر على النظام حذف الحساب “[_1]”. لا يمكن حذف نوع الحساب “[_2]”.","The system could not determine the service type for the “[_1]” service account.":"تعذر على النظام تحديد نوع الخدمة لحساب الخدمة “[_1]”.","The system detected an unknown service for the “[_1]” service account.":"اكتشف النظام خدمة غير معروفة لحساب الخدمة “[_1]”.","The system failed to determine whether the username is available: [_1]":"فشل النظام في تحديد ما إذا كان اسم المستخدم متاحًا أم لا: [_1]","The username is not available.":"اسم المستخدم غير متاح.","This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.":"This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.","This user has not used the invitation to set a password.":"This user has not used the invitation to set a password.","Web Disk":"Web Disk","cPanel Account":"حساب cPanel"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
