//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/services/userService-ru.js
// Module:    /paper_lantern/user_manager/services/userService-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Email":"Электронная почта","FTP":"FTP","Hypothetical Subaccount":"Гипотетическая дополнительная учетная запись","Invite Expired":"Invite Expired","Invite Pending":"Invite Pending","Service Account":"Учетная запись службы","Subaccount":"Дополнительная учетная запись","The system could not delete the “[_1]” account. You cannot delete the “[_2]” account type.":"Системе не удалось удалить учетную запись «[_1]». Нельзя удалить тип учетной записи «[_2]».","The system could not determine the service type for the “[_1]” service account.":"Системе не удалось определить тип службы для учетной записи службы «[_1]».","The system detected an unknown service for the “[_1]” service account.":"Система обнаружила неизвестную службу для учетной записи службы «[_1]».","The system failed to determine whether the username is available: [_1]":"Не удалось определить доступность имени пользователя: [_1]","The username is not available.":"Имя пользователя недоступно.","This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.":"This user did not respond to the invitation before it expired. Please delete and re-create the user to send another invitation or set the user’s password yourself.","This user has not used the invitation to set a password.":"This user has not used the invitation to set a password.","Web Disk":"Web Disk","cPanel Account":"Учетная запись cPanel"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
