//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/passenger/views/details.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/passenger/views/details-tr.js
// Module:    /paper_lantern/passenger/views/details-tr
// Locale:    tr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add":"Ekle","Add an Application":"Add an Application","Edit":"Düzenle","Edit Application “[_1]”":"Edit Application “[_1]”","You successfully added the application configuration for “[_1]”.":"You successfully added the application configuration for “[_1]”.","You successfully updated the application configuration for “[_1]”.":"You successfully updated the application configuration for “[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
