//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/passenger/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/passenger/index.cmb-uk.js
// Module:    /paper_lantern/passenger/index.cmb-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add":"Додати","Add an Application":"Add an Application","Addon Domains":"Додаткові домени","Are you certain that you want to delete the application configuration for “[_1]”?":"Are you certain that you want to delete the application configuration for “[_1]”?","Edit":"Редагувати","Edit Application “[_1]”":"Edit Application “[_1]”","Main Domain":"Основний домен","Other":"Інше","Subdomains":"Дочірні домени","The [asis,Base URI] must begin with a single slash ([asis,/]) and may not contain spaces, special characters or a trailing slash.":"The [asis,Base URI] must begin with a single slash ([asis,/]) and may not contain spaces, special characters or a trailing slash.","The application, “[_1]”, is now disabled.":"The application, “[_1]”, is now disabled.","The application, “[_1]”, is now enabled.":"The application, “[_1]”, is now enabled.","You reached your account’s allotment of applications, [numf,_1].":"You reached your account’s allotment of applications, [numf,_1].","You successfully added the application configuration for “[_1]”.":"You successfully added the application configuration for “[_1]”.","You successfully deleted the application configuration for “[_1]”.":"You successfully deleted the application configuration for “[_1]”.","You successfully updated the application configuration for “[_1]”.":"You successfully updated the application configuration for “[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
