//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/passenger/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/passenger/index.cmb-no.js
// Module:    /paper_lantern/passenger/index.cmb-no
// Locale:    no
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Addon Domains":"Addon Domains","Are you certain that you want to unregister the application “[_1]”?":"Are you certain that you want to unregister the application “[_1]”?","Edit":"Edit","Edit Application “[_1]”":"Edit Application “[_1]”","Main Domain":"Main Domain","Other":"Other","Register":"Register","Register an Application":"Register an Application","Subdomains":"Subdomains","The [asis,Base URI] must begin with a single slash ([asis,/]) and may not contain spaces, special characters or a trailing slash.":"The [asis,Base URI] must begin with a single slash ([asis,/]) and may not contain spaces, special characters or a trailing slash.","The application, “[_1]”, is now disabled.":"The application, “[_1]”, is now disabled.","The application, “[_1]”, is now enabled.":"The application, “[_1]”, is now enabled.","You reached your account’s allotment of applications, [numf,_1].":"You reached your account’s allotment of applications, [numf,_1].","You successfully registered the application “[_1]”.":"You successfully registered the application “[_1]”.","You successfully unregistered the application “[_1]”.":"You successfully unregistered the application “[_1]”.","You successfully updated the application “[_1]”.":"You successfully updated the application “[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
