//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/filters/incomingSuspendedTooltip.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/filters/incomingSuspendedTooltip-fr.js
// Module:    /paper_lantern/mail/pops/filters/incomingSuspendedTooltip-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"“[_1]” can receive mail.":"« [_1] » peut recevoir des e-mails.","“[_1]” is suspended from receiving mail.":"La réception d’e-mails est suspendue pour « [_1] »."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
