//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/filters/loginSuspendedTooltip.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/filters/loginSuspendedTooltip-es.js
// Module:    /paper_lantern/mail/pops/filters/loginSuspendedTooltip-es
// Locale:    es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"“[_1]” can send and receive mail.":"“[_1]” puede enviar y recibir correo.","“[_1]” is suspended from sending and reading mail.":"“[_1]” está suspendido del envío y la lectura de mensajes de correo."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
