//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/filters/loginIncomingTooltip.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/filters/loginIncomingTooltip-pt_br.js
// Module:    /paper_lantern/mail/pops/filters/loginIncomingTooltip-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Allow “[_1]” to log in and to receive mail.":"Permita que “[_1]” faça login e receba email.","Suspend “[_1]”’s logins and incoming mail.":"Suspender logins e emails de entrada de “[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
