//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/index.cmb-pl.js
// Module:    /paper_lantern/multiphp_ini_editor/index.cmb-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Apply":"Zastosuj","Disabled":"Wyłączono","Enabled":"Włączony","Save":"Zapisz","Successfully applied the settings.":"Pomyślnie zastosowano ustawienia.","Successfully saved the changes.":"Pomyślnie zapisano zmiany.","The [asis,INI] content does not exist. You may add new content.":"Nie istnieje treść pliku [asis,INI]. Można dodać nową treść.","You must click “[_1]” to apply the new changes.":"Aby zastosować nowe zmiany, należy kliknąć przycisk „[_1]”.","You must provide a valid float value.":"You must provide a valid float value.","You must provide either an integer value, a [output,url,_1,shorthand byte,target,blank,title,shorthand byte documentation], or a [output,url,_2,predefined constant,target,blank,title,predefined constant documentation].":"You must provide either an integer value, a [output,url,_1,shorthand byte,target,blank,title,shorthand byte documentation], or a [output,url,_2,predefined constant,target,blank,title,predefined constant documentation].","[asis,PHP] Default: [output,class,_1,defaultValue]":"Domyślne ustawienie języka [asis,PHP]: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]— Niedostępne —[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]— Wybierz lokalizację —[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
