//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/index.cmb-ja.js
// Module:    /paper_lantern/multiphp_ini_editor/index.cmb-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Apply":"適用","Disabled":"無効","Enabled":"有効","Save":"保存","Successfully applied the settings.":"設定が正常に適用されました。","Successfully saved the changes.":"変更が正常に保存されました。","The [asis,INI] content does not exist. You may add new content.":"[asis,INI] のコンテンツが存在しません。新しいコンテンツを追加することができます。","You must click “[_1]” to apply the new changes.":"新しい変更を適用するには、“[_1]” をクリックする必要があります。","You must provide a valid float value.":"You must provide a valid float value.","You must provide either an integer value, a [output,url,_1,shorthand byte,target,blank,title,shorthand byte documentation], or a [output,url,_2,predefined constant,target,blank,title,predefined constant documentation].":"You must provide either an integer value, a [output,url,_1,shorthand byte,target,blank,title,shorthand byte documentation], or a [output,url,_2,predefined constant,target,blank,title,predefined constant documentation].","[asis,PHP] Default: [output,class,_1,defaultValue]":"[asis,PHP]既定: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- 利用できません --[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- 場所を選択します --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
