<div id="test-1">
    <uib-pagination
        id="test-1-id"
        total-items="totalItems"
        ng-model="currentPage"
        max-size="50"
        boundary-links="true"
        rotate="false"
        previous-text="<"
        next-text=">"
        first-text="<<"
        last-text=">>"
        items-per-page="pageSize"
        ng-change="selectPage()"
        ng-disabled="isDisabled">
    </uib-pagination>
</div>