//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/email_accounts/services/emailAccountsService.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/email_accounts/services/emailAccountsService-th.js
// Module:    /paper_lantern/email_accounts/services/emailAccountsService-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Email account “[_1]” is up to date.":"Email account “[_1]” is up to date.","We can’t hold mail for “[_1]”:“[_2]”":"We can’t hold mail for “[_1]”:“[_2]”","We can’t suspend incoming mail for “[_1]”:“[_2]”":"We can’t suspend incoming mail for “[_1]”:“[_2]”","We can’t suspend logins for “[_1]”:“[_2]”":"We can’t suspend logins for “[_1]”:“[_2]”","We can’t suspend outgoing mail for “[_1]”:“[_2]”":"We can’t suspend outgoing mail for “[_1]”:“[_2]”","We can’t unsuspend incoming mail for “[_1]”:“[_2]”":"We can’t unsuspend incoming mail for “[_1]”:“[_2]”","We can’t unsuspend logins for “[_1]”:“[_2]”":"We can’t unsuspend logins for “[_1]”:“[_2]”","We can’t unsuspend outgoing mail for “[_1]”:“[_2]”":"We can’t unsuspend outgoing mail for “[_1]”:“[_2]”","We can’t update the password for “[_1]”:“[_2]”":"We can’t update the password for “[_1]”:“[_2]”","We can’t update the storage space for “[_1]”:“[_2]”":"We can’t update the storage space for “[_1]”:“[_2]”","We’re holding outgoing mail for “[_1]”.":"We’re holding outgoing mail for “[_1]”.","You do not have an email account named “[_1]”.":"You do not have an email account named “[_1]”.","You suspended incoming mail for “[_1]”.":"You suspended incoming mail for “[_1]”.","You suspended logins for “[_1]”.":"You suspended logins for “[_1]”.","You suspended outgoing mail for “[_1]”.":"You suspended outgoing mail for “[_1]”.","You unsuspended incoming mail for “[_1]”.":"You unsuspended incoming mail for “[_1]”.","You unsuspended logins for “[_1]”.":"You unsuspended logins for “[_1]”.","You unsuspended outgoing mail for “[_1]”.":"You unsuspended outgoing mail for “[_1]”.","You updated the password for “[_1]”.":"You updated the password for “[_1]”.","You updated the storage space for “[_1]”.":"You updated the storage space for “[_1]”.","[quant,_1,message has,messages have] been queued for deletion from the outgoing mail queue.":"[quant,_1,message has,messages have] been queued for deletion from the outgoing mail queue."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
