//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/basicMode.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/basicMode-fil.js
// Module:    /paper_lantern/multiphp_ini_editor/views/basicMode-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Apply":"Ilapat","Disabled":"Naka-disable","Enabled":"Naka-enable ang","Errors occurred while retrieving the [asis,PHP INI] locations.":"Errors occurred while retrieving the [asis,PHP INI] locations.","Successfully applied the settings.":"Successfully applied the settings.","You must click “[_1]” to apply the new changes.":"You must click “[_1]” to apply the new changes.","You must provide a valid float value.":"You must provide a valid float value.","You must provide either an integer value, a [output,url,_1,shorthand byte,target,blank,title,shorthand byte documentation], or a [output,url,_2,predefined constant,target,blank,title,predefined constant documentation].":"You must provide either an integer value, a [output,url,_1,shorthand byte,target,blank,title,shorthand byte documentation], or a [output,url,_2,predefined constant,target,blank,title,predefined constant documentation].","[asis,PHP] Default: [output,class,_1,defaultValue]":"[asis,PHP] Default: [output,class,_1,defaultValue]","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
