//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/editorMode.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/editorMode-pt_br.js
// Module:    /paper_lantern/multiphp_ini_editor/views/editorMode-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Save":"Salvar","Successfully saved the changes.":"As alterações foram salvas com êxito.","The [asis,INI] content does not exist. You may add new content.":"O conteúdo do [asis,INI] não existe. Você pode adicionar novo conteúdo.","You must click “[_1]” to apply the new changes.":"Clique em “[_1]” para aplicar as novas alterações.","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]– Não disponível –[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]– Selecione um local –[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
