//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/editorMode.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/editorMode-fi.js
// Module:    /paper_lantern/multiphp_ini_editor/views/editorMode-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Save":"Tallenna","Successfully saved the changes.":"Muutosten tallennus onnistui.","The [asis,INI] content does not exist. You may add new content.":"[asis,INI]-sisältöä ei ole. Voit lisätä uutta sisältöä.","You must click “[_1]” to apply the new changes.":"Ota uudet muutokset käyttöön valitsemalla [_1].","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]- Ei käytettävissä -[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- Valitse toiminto --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
