//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/editorMode.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/multiphp_ini_editor/views/editorMode-ar.js
// Module:    /paper_lantern/multiphp_ini_editor/views/editorMode-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Save":"حفظ","Successfully saved the changes.":"تم حفظ التغييرات بنجاح.","The [asis,INI] content does not exist. You may add new content.":"محتوى [asis,INI] غير موجود. يمكنك إضافة محتوى جديد.","You must click “[_1]” to apply the new changes.":"يجب عليك النقر فوق “[_1]” لتطبيق هذه التغييرات.","[comment,used for highlight in select option]-- Not Available --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- غير متوفر --[comment,used for highlight in select option]","[comment,used for highlight in select option]-- Select a location --[comment,used for highlight in select option]":"[comment,used for highlight in select option]-- تحديد موقع --[comment,used for highlight in select option]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
