//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter-el.js
// Module:    /paper_lantern/js2/mail/filters/editfilter-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Browse":"Περιήγηση","Cancel":"Άκυρο","Filter Name":"Όνομα φίλτρου","Saving filter “[output,class,_1,code]” …":"Αποθήκευση φίλτρου «[output,class,_1,code]» …","Success! The filters list is reloading now.":"Επιτυχία! Η λίστα φίλτρων φορτώνεται ξανά τώρα.","The filter name cannot be empty.":"Το όνομα φίλτρου δεν πρέπει να είναι κενό.","The filter name cannot contain “[output,class,_1,code]” or “[output,class,_2,code]”.":"Το όνομα φίλτρου δεν πρέπει να περιέχει «[output,class,_1,code]» ή «[output,class,_2,code]».","You have successfully created a new filter. You can create another one now, or you can [output,url,_1,return to the filters list].":"Δημιουργήσατε με επιτυχία ένα νέο φίλτρο. Τώρα, μπορείτε να δημιουργήσετε ακόμη ένα ή να [output,url,_1,επιστρέψετε στη λίστα φίλτρων]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
