//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter-it.js
// Module:    /paper_lantern/js2/mail/filters/editfilter-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Browse":"Cerca","Cancel":"Annulla","Filter Name":"Nome filtro","Saving filter “[output,class,_1,code]” …":"Salvataggio del filtro “[output,class,_1,code]” in corso…","Success! The filters list is reloading now.":"Operazione completata Ricaricamento dell’elenco dei filtri.","The filter name cannot be empty.":"Il campo del nome del filtro non può essere vuoto.","The filter name cannot contain “[output,class,_1,code]” or “[output,class,_2,code]”.":"Il nome del filtro non può contenere “[output,class,_1,code]” o “[output,class,_2,code]”.","You have successfully created a new filter. You can create another one now, or you can [output,url,_1,return to the filters list].":"Creazione di un nuovo filtro completata. È possibile crearne un altro ora oppure è possibile [output,url,_1,tornare all’elenco dei filtri]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
