//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter-es_es.js
// Module:    /paper_lantern/js2/mail/filters/editfilter-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Browse":"Examinar","Cancel":"Cancelar","Filter Name":"Nombre del filtro","Saving filter “[output,class,_1,code]” …":"Guardando filtro “[output,class,_1,code]”…","Success! The filters list is reloading now.":"¡Sin errores! La lista de filtros se está recargando ahora.","The filter name cannot be empty.":"El nombre de filtro no puede estar vacío.","The filter name cannot contain “[output,class,_1,code]” or “[output,class,_2,code]”.":"El nombre del filtro no puede contener “[output,class,_1,code]” o “[output,class,_2,code]”.","You have successfully created a new filter. You can create another one now, or you can [output,url,_1,return to the filters list].":"Ha creado correctamente un nuevo filtro. Puede crear otro ahora o puede [output,url,_1,volver a la lista de filtros]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
