//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/filters/editfilter-uk.js
// Module:    /paper_lantern/js2/mail/filters/editfilter-uk
// Locale:    uk
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Browse":"Огляд","Cancel":"Скасувати","Filter Name":"Ім’я фільтра","Saving filter “[output,class,_1,code]” …":"Збереження фільтра „[output,class,_1,code]”…","Success! The filters list is reloading now.":"Вітаємо! Список фільтрів наразі перезавантажується.","The filter name cannot be empty.":"Ім’я фільтра не може бути пустим.","The filter name cannot contain “[output,class,_1,code]” or “[output,class,_2,code]”.":"Ім’я фільтра не може містити „[output,class,_1,code]” або „[output,class,_2,code]”.","You have successfully created a new filter. You can create another one now, or you can [output,url,_1,return to the filters list].":"Ви успішно створили новий фільтр. Ви можете продовжити створювати фільтри або [output,url,_1,повернутися до списку фільтрів]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
