//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/accounts.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/accounts-el.js
// Module:    /paper_lantern/js2/ftp/accounts-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"Σφάλμα AJAX","Actions":"Ενέργειες","Error":"Σφάλμα","JSON parse failed.":"Η ανάλυση JSON απέτυχε.","Loading …":"Φόρτωση…","Log In":"Σύνδεση","Path":"Διαδρομή","Please refresh the page and try again.":"Ανανεώστε τη σελίδα και δοκιμάστε πάλι.","Quota":"Όριο","The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.":"The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.","The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.":"The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.","The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.":"The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.","Type":"Τύπος","Unknown Error":"Άγνωστο σφάλμα","Usage":"Χρήση","You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].":"You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].","You must enter an [output,acronym,FTP,File Transfer Protocol] username.":"You must enter an [output,acronym,FTP,File Transfer Protocol] username."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
