//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp-it.js
// Module:    /paper_lantern/js2/ftp/list_ftp-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"Errore AJAX","Actions":"Azioni","Error":"Errore","JSON parse failed.":"Analisi JSON non riuscita.","Loading …":"Caricamento in corso…","Log In":"Accedi","Path":"Percorso","Please refresh the page and try again.":"Aggiornare la pagina e riprovare.","Quota":"Quota","The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.":"Il nome utente [output,acronym,FTP,File Transfer Protocol] non può essere costituito da più di [numf,_1] caratteri.","The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.":"Il nome utente [output,acronym,FTP,File Transfer Protocol] non può iniziare con un punto, terminare con un punto o includere punti consecutivi.","The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.":"Il nome utente [output,acronym,FTP,File Transfer Protocol] completo con il dominio associato non può essere costituito da più di [numf,_1] caratteri.","Type":"Tipo","Unknown Error":"Errore sconosciuto","Usage":"Utilizzo","You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].":"È possibile immettere solo lettere [asis,(a-z)], numeri [asis,(0-9)], punti, trattini [asis,(-)] e caratteri di sottolineatura [asis,(_)].","You must enter an [output,acronym,FTP,File Transfer Protocol] username.":"È necessario inserire un nome utente [output,acronym,FTP,File Transfer Protocol]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
