//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp-sv.js
// Module:    /paper_lantern/js2/ftp/list_ftp-sv
// Locale:    sv
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX-fel","Actions":"Åtgärder","Error":"Fel","JSON parse failed.":"JSON-parsning misslyckades.","Loading …":"Läser in …","Log In":"Logga in","Path":"Sökväg","Please refresh the page and try again.":"Uppdatera sidan och försök igen.","Quota":"Kvot","The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.":"The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.","The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.":"The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.","The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.":"The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.","Type":"Typ","Unknown Error":"Okänt fel","Usage":"Användning","You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].":"You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].","You must enter an [output,acronym,FTP,File Transfer Protocol] username.":"You must enter an [output,acronym,FTP,File Transfer Protocol] username."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
