//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp-pt_br.js
// Module:    /paper_lantern/js2/ftp/list_ftp-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"Erro AJAX","Actions":"Ações","Error":"Erro","JSON parse failed.":"Falha na análise JSON.","Loading …":"Carregando…","Log In":"Fazer login","Path":"Caminho","Please refresh the page and try again.":"Atualize a página e tente novamente.","Quota":"Cota","The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.":"O nome de usuário do [output,acronym,FTP,File Transfer Protocol] não pode exceder [numf,_1] caracteres.","The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.":"O nome de usuário do [output,acronym,FTP,File Transfer Protocol] não pode começar com um ponto, terminar com um ponto nem incluir dois pontos consecutivos.","The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.":"O nome completo do usuário de [output,acronym,FTP,File Transfer Protocol] com seu domínio associado não pode exceder [numf,_1] caracteres.","Type":"Tipo","Unknown Error":"Erro desconhecido","Usage":"Uso","You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].":"Você só pode usar letras [asis,(a-z)], números [asis,(0-9)], pontos, hifens [asis,(-)] e sublinhados [asis,(_)].","You must enter an [output,acronym,FTP,File Transfer Protocol] username.":"Você deve informar um nome de usuário de [output,acronym,FTP,File Transfer Protocol]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
