//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/ftp/list_ftp-th.js
// Module:    /paper_lantern/js2/ftp/list_ftp-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"ข้อผิดพลาด AJAX","Actions":"การกระทำ","Error":"ข้อผิดพลาด","JSON parse failed.":"การแยกวิเคราะห์ JSON ล้มเหลว","Loading …":"กำลังโหลด …","Log In":"เข้าสู่ระบบ","Path":"เส้นทาง","Please refresh the page and try again.":"โปรดรีเฟรชหน้าและลองอีกครั้ง","Quota":"โควตา","The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.":"The [output,acronym,FTP,File Transfer Protocol] username cannot exceed [numf,_1] characters.","The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.":"The [output,acronym,FTP,File Transfer Protocol] username cannot start with a period, end with a period, or include two consecutive periods.","The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.":"The full [output,acronym,FTP,File Transfer Protocol] username with its associated domain cannot exceed [numf,_1] characters.","Type":"ชนิด","Unknown Error":"ข้อผิดพลาดที่ไม่รู้จัก","Usage":"การใช้งาน","You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].":"You can only enter letters [asis,(a-z)], numbers [asis,(0-9)], periods, hyphens [asis,(-)], and underscores [asis,(_)].","You must enter an [output,acronym,FTP,File Transfer Protocol] username.":"You must enter an [output,acronym,FTP,File Transfer Protocol] username."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
