//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb-th.js
// Module:    /paper_lantern/mail/lists/lists.cmb-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"การเข้าถึง","Admin":"ผู้ดูแลระบบ","Edit Privacy Options: “[_1]”":"แก้ไขตัวเลือกส่วนตัว: “[_1]”","Functions":"ฟังก์ชัน","List Name":"ชื่อรายการ","Saving …":"กำลังบันทึก …","Usage":"การใช้งาน","[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1] … และ [numf,_3] อีก"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
