//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb-zh.js
// Module:    /paper_lantern/mail/lists/lists.cmb-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"访问","Admin":"管理员","Edit Privacy Options: “[_1]”":"编辑隐私选项:“[_1]”","Functions":"功能","List Name":"列表名称","Saving …":"正在保存…","Usage":"使用情况","[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1] … 以及 [numf,_3] 更多内容"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
