//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb-pt.js
// Module:    /paper_lantern/mail/lists/lists.cmb-pt
// Locale:    pt
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"Access","Admin":"Admin","Edit Privacy Options: “[_1]”":"Edit Privacy Options: “[_1]”","Functions":"Funções","List Name":"List Name","Saving …":"Salvando ...","Usage":"Usage","[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1] … and [numf,_3] more"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
