//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb-da.js
// Module:    /paper_lantern/mail/lists/lists.cmb-da
// Locale:    da
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"Adgang","Admin":"Administrator","Edit Privacy Options: “[_1]”":"Rediger indstillinger for beskyttelse af personlige oplysninger: ”[_1]”","Functions":"Funktioner","List Name":"Listenavn","Saving …":"Gemmer …","Usage":"Forbrug","[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1]… og [numf,_3] mere"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
