//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/lists/lists.cmb-de.js
// Module:    /paper_lantern/mail/lists/lists.cmb-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Access":"Zugriff","Admin":"Administrator","Edit Privacy Options: “[_1]”":"Datenschutzoptionen bearbeiten: „[_1]“","Functions":"Funktionen","List Name":"Listenname","Saving …":"Speicherung läuft…","Usage":"Nutzung","[join,_1,_2][_1] … and [numf,_3] more":"[join,_1,_2][_1] … und [numf,_3] mehr"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
