//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/site_publisher/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/site_publisher/index.cmb-de.js
// Module:    /paper_lantern/site_publisher/index.cmb-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"A problem has occurred: [_1]":"Es ist ein Fehler ist aufgetreten: [_1]","The form has returned [quant,_1,error,errors]":"Das Formular hat [quant,_1,Fehler,Fehler] zurückgegeben."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
