//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController-ru.js
// Module:    /paper_lantern/security/mod_security/views/domainListController-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,ModSecurity™] on all domains.":"Вы успешно отключили [asis,ModSecurity™] во всех доменах.","Successfully disabled [asis,ModSecurity™] on “[_1]”.":"Вы успешно отключили [asis,ModSecurity™] в «[_1]».","Successfully enabled [asis,ModSecurity™] on all domains.":"Вы успешно включили [asis,ModSecurity™] во всех доменах.","Successfully enabled [asis,ModSecurity™] on “[_1]”.":"Вы успешно включили [asis,ModSecurity™] в «[_1]»."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
