//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController-ko.js
// Module:    /paper_lantern/security/mod_security/views/domainListController-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,ModSecurity™] on all domains.":"모든 도메인에서 [asis,ModSecurity™]을(를) 비활성화했습니다.","Successfully disabled [asis,ModSecurity™] on “[_1]”.":"“[_1]”에서 [asis,ModSecurity™]을(를) 비활성화했습니다.","Successfully enabled [asis,ModSecurity™] on all domains.":"모든 도메인에서 [asis,ModSecurity™]을(를) 활성화했습니다.","Successfully enabled [asis,ModSecurity™] on “[_1]”.":"“[_1]”에서 [asis,ModSecurity™]을(를) 활성화했습니다."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
