//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController-fil.js
// Module:    /paper_lantern/security/mod_security/views/domainListController-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,ModSecurity™] on all domains.":"Matagumpay na na-disable ang [asis,ModSecurity™] sa lahat ng domain.","Successfully disabled [asis,ModSecurity™] on “[_1]”.":"Matagumpay na na-disable ang [asis,ModSecurity™] sa “[_1]”.","Successfully enabled [asis,ModSecurity™] on all domains.":"Matagumpay na na-enable ang [asis,ModSecurity™] sa lahat ng domain.","Successfully enabled [asis,ModSecurity™] on “[_1]”.":"Matagumpay na na-enable ang [asis,ModSecurity™] sa “[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
