//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/views/domainListController-de.js
// Module:    /paper_lantern/security/mod_security/views/domainListController-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,ModSecurity™] on all domains.":"[asis,ModSecurity™] wurde in allen Domänen erfolgreich deaktiviert.","Successfully disabled [asis,ModSecurity™] on “[_1]”.":"[asis,ModSecurity™] wurde in „[_1]“ erfolgreich deaktiviert.","Successfully enabled [asis,ModSecurity™] on all domains.":"[asis,ModSecurity™] wurde in allen Domänen erfolgreich aktiviert.","Successfully enabled [asis,ModSecurity™] on “[_1]”.":"[asis,ModSecurity™] wurde in „[_1]“ erfolgreich aktiviert."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
