//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/domains/validators/subdomain.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/domains/validators/subdomain-zh_tw.js
// Module:    /paper_lantern/domains/validators/subdomain-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The server reserves this subdomain for system use only. Enter a different subdomain.":"The server reserves this subdomain for system use only. Enter a different subdomain.","You must enter a valid subdomain.":"You must enter a valid subdomain."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
