//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/spam/services/spamAssassin.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/spam/services/spamAssassin-no.js
// Module:    /paper_lantern/mail/spam/services/spamAssassin-no
// Locale:    no
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"All Spam Box folders expunged.":"All Spam Box folders expunged.","Expunged the Spam Box folder for “[_1]”.":"Expunged the Spam Box folder for “[_1]”.","Spam Auto-Delete has been disabled.":"Spam Auto-Delete has been disabled.","Spam Auto-Delete has been enabled.":"Spam Auto-Delete has been enabled.","Spam Box has been disabled.":"Spam Box has been disabled.","Spam Box has been enabled.":"Spam Box has been enabled.","The Auto-Delete Threshold Score has been updated to [_1].":"The Auto-Delete Threshold Score has been updated to [_1].","The [asis,Apache SpamAssassin] user preferences have been updated.":"The [asis,Apache SpamAssassin] user preferences have been updated.","[asis,Apache SpamAssassin] has been disabled.":"[asis,Apache SpamAssassin] has been disabled.","[asis,Apache SpamAssassin] has been enabled.":"[asis,Apache SpamAssassin] has been enabled."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
