//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/issueList.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/issueList-pl.js
// Module:    /paper_lantern/user_manager/directives/issueList-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Error:":"Błąd:","Mail Quota Reached:":"Osiągnięto limit poczty:","Mail Quota Warning:":"Ostrzeżenie dotyczące limitu poczty:","Warning:":"Ostrzeżenie:","[asis,FTP] Quota Reached:":"Osiągnięto limit konta [asis,FTP]:","[asis,FTP] Quota Warning:":"Ostrzeżenie dotyczące limitu konta [asis,FTP]:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
