//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/issueList.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/issueList-ar.js
// Module:    /paper_lantern/user_manager/directives/issueList-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Error:":"خطأ:","Mail Quota Reached:":"وصل البريد إلى الحصة النسبية:","Mail Quota Warning:":"تحذير الحصة النسبية للبريد:","Warning:":"تحذير:","[asis,FTP] Quota Reached:":"تم الوصول إلى حصة [asis,FTP] النسبية:","[asis,FTP] Quota Warning:":"[asis,FTP] تحذير الحصة النسبية:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
