//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/issueList.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/issueList-es.js
// Module:    /paper_lantern/user_manager/directives/issueList-es
// Locale:    es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Error:":"Error:","Mail Quota Reached:":"Se alcanzó la cuota de correo:","Mail Quota Warning:":"Advertencia de cuota de correo:","Warning:":"Advertencia:","[asis,FTP] Quota Reached:":"Se ha alcanzado la cuota de [asis,FTP]:","[asis,FTP] Quota Warning:":"[asis,FTP] Advertencia de cuota:"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
