//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/validateUsernameWithDomain.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/directives/validateUsernameWithDomain-nl.js
// Module:    /paper_lantern/user_manager/directives/validateUsernameWithDomain-nl
// Locale:    nl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The combined length of the username, [asis,@] character, and domain cannot exceed [numf,_1] characters.":"De gecombineerde lengte van de gebruikersnaam, het [asis,@]-teken en het domein mag niet meer dan [numf,_1] tekens bedragen."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
