//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist-el.js
// Module:    /paper_lantern/js2/mail/delegatelist-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Saving …":"Αποθήκευση…","The data on this page is no longer synchronized with the server. Please [output,url,_1,refresh the page].":"Τα δεδομένα αυτής της σελίδας δεν είναι πλέον συγχρονισμένα με το διακομιστή. [output,url,_1,Ανανεώστε τη σελίδα].","You have successfully updated delegation of administrative privileges for the mailing list “[_1]”.":"Ενημερώσατε με επιτυχία την ανάθεση δικαιωμάτων διαχείρισης για τη λίστα αλληλογραφίας «[_1]»."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
