//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist-es_419.js
// Module:    /paper_lantern/js2/mail/delegatelist-es_419
// Locale:    es_419
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Saving …":"Guardando…","The data on this page is no longer synchronized with the server. Please [output,url,_1,refresh the page].":"Los datos de esta página ya no están sincronizados con el servidor. [output,url,_1,Actualice la página].","You have successfully updated delegation of administrative privileges for the mailing list “[_1]”.":"Actualizó los privilegios de administración de la delegación de esta lista de correo electrónico correctamente“[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
