//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist-pl.js
// Module:    /paper_lantern/js2/mail/delegatelist-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Saving …":"Zapisywanie…","The data on this page is no longer synchronized with the server. Please [output,url,_1,refresh the page].":"Dane na tej stronie nie są już zsynchronizowane z serwerem. [output,url,_1,Odśwież stronę].","You have successfully updated delegation of administrative privileges for the mailing list “[_1]”.":"Pomyślnie zaktualizowano delegowanie uprawnień administracyjnych wobec listy wysyłkowej „[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
