//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist-th.js
// Module:    /paper_lantern/js2/mail/delegatelist-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Saving …":"กำลังบันทึก …","The data on this page is no longer synchronized with the server. Please [output,url,_1,refresh the page].":"ข้อมูลบนหน้านี้ไม่ได้รับการซิงโครไนซ์กับเซิร์ฟเวอร์อีกต่อไป โปรด [output,url,_1,รีเฟรชหน้า]","You have successfully updated delegation of administrative privileges for the mailing list “[_1]”.":"คุณได้อัพเดตการมอบสิทธิ์ของสิทธิ์การดูแลระบบสำหรับรายชื่อผู้รับจดหมาย “[_1]”"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
