//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/delegatelist-zh.js
// Module:    /paper_lantern/js2/mail/delegatelist-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Saving …":"正在保存…","The data on this page is no longer synchronized with the server. Please [output,url,_1,refresh the page].":"此页面上的数据不再与服务器同步。 请[output,url,_1,刷新页面]。","You have successfully updated delegation of administrative privileges for the mailing list “[_1]”.":"已成功更新邮件列表“[_1]”管理权限的委派。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
