//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/pops.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/mail/pops-zh.js
// Module:    /paper_lantern/js2/mail/pops-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX 错误","Account Name":"帐户名称","Allow “[_1]” to log in and to receive mail.":"允许“[_1]”登录并接收邮件。","Allow “[_1]” to log in.":"允许“[_1]”登录。","Allow “[_1]” to receive mail.":"允许“[_1]”接收邮件。","Communication failure: [_1]":"通信失败: [_1]","Domain":"域","Error":"错误","JSON parse failed.":"JSON 分析失败。","Loading …":"正在加载…","Manage Disk Usage":"Manage Disk Usage","Manage External Authentication":"管理外部身份验证","Password cannot have spaces.":"密码不能有空格。","Password strength must be at least [numf,_1].":"密码强度必须至少为 [numf,_1]。","Passwords Match":"密码匹配","Passwords do not match.":"密码不匹配。","Please refresh the page and try again.":"请刷新页面然后重试。","Suspend":"暂停","Suspend Incoming Mail":"暂停接收邮件","Suspend Login":"暂停登录","Suspend “[_1]” from receiving mail.":"暂停“[_1]”接收邮件。","Suspend “[_1]”’s logins and incoming mail.":"暂停“[_1]”的登录名和接收邮件。","Suspend “[_1]”’s logins.":"暂停“[_1]”的登录名。","The email address cannot exceed [numf,_1] characters.":"电子邮件地址不能超过 [numf,_1] 个字符。","The mailbox name cannot exceed [numf,_1] characters.":"邮箱名称不能超过 [numf,_1] 个字符。","The mailbox name cannot start with a period, end with a period, or include two consecutive periods.":"邮箱名称不能以句点开头或结尾，也不能包含两个连续的句点。","Unknown Error":"未知错误","Unlimited":"无限制","Unsuspend":"取消暂停","Unsuspend Incoming Mail":"取消暂停接收邮件","Unsuspend Login":"取消暂停登录","You can only enter letters, numbers, periods, hyphens, and underscores.":"您只能输入字母、数字、句点、连字符和下划线。","You must enter a mailbox name.":"必须输入邮箱名称。","“[_1]” can receive mail.":"“[_1]”可以接收邮件。","“[_1]” can send and receive mail.":"“[_1]”可以发送和接收邮件。","“[_1]” is suspended from receiving mail.":"已暂停“[_1]”接收邮件。","“[_1]” is suspended from sending and reading mail.":"已暂停“[_1]”发送和阅读邮件。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
