//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/index.cmb-bg.js
// Module:    /paper_lantern/security/mod_security/index.cmb-bg
// Locale:    bg
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,ModSecurity™] on all domains.":"Successfully disabled [asis,ModSecurity™] on all domains.","Successfully disabled [asis,ModSecurity™] on “[_1]”.":"Successfully disabled [asis,ModSecurity™] on “[_1]”.","Successfully enabled [asis,ModSecurity™] on all domains.":"Successfully enabled [asis,ModSecurity™] on all domains.","Successfully enabled [asis,ModSecurity™] on “[_1]”.":"Successfully enabled [asis,ModSecurity™] on “[_1]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
