//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/security/mod_security/index.cmb-ja.js
// Module:    /paper_lantern/security/mod_security/index.cmb-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,ModSecurity™] on all domains.":"すべてのドメインの [asis,ModSecurity™] が正常に無効になりました。","Successfully disabled [asis,ModSecurity™] on “[_1]”.":"“[_1]” の [asis,ModSecurity™] が正常に無効になりました。","Successfully enabled [asis,ModSecurity™] on all domains.":"すべてのドメインの [asis,ModSecurity™] が正常に有効になりました。","Successfully enabled [asis,ModSecurity™] on “[_1]”.":"“[_1]” の [asis,ModSecurity™] が正常に有効になりました。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
