//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/views/addController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/views/addController-de.js
// Module:    /paper_lantern/user_manager/views/addController-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The system failed to create the “[_1]” user with the following error: [_2]":"Die Erstellung des Benutzers „[_1]“ ist mit folgendem Fehler fehlgeschlagen: [_2]","You successfully created the following user: [_1]":"Der folgende Benutzer wurde erfolgreich erstellt: [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
