//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/views/listController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/views/listController-nl.js
// Module:    /paper_lantern/user_manager/views/listController-nl
// Locale:    nl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Do you wish to remove the “[_1]” user from your system?":"Wilt u de gebruiker ’[_1]’ van uw systeem verwijderen’?","The service account is invalid.":"De serviceaccount is ongeldig.","The system successfully linked all of the service accounts for the “[_1]” user to the [asis,subaccount]. The service account passwords did not change.":"Alle serviceaccounts voor de gebruiker ’[_1]’ zijn gekoppeld aan de [asis,subaccount]. De serviceaccountwachtwoorden zijn niet gewijzigd.","The system successfully linked all of the service accounts for the “[_1]” user to the [asis,subaccount]. The service account passwords did not change. You must provide a new password if you wish to enable any additional [asis,subaccount] services.":"Alle serviceaccounts voor de gebruiker ’[_1]’ zijn gekoppeld aan de [asis,subaccount]. De serviceaccountwachtwoorden zijn niet gewijzigd. U moet een nieuw wachtwoord opgeven als u extra [asis,subaccount]-services wilt inschakelen.","The system successfully linked the service account to the “[_1]” user’s [asis,subaccount]. The service account passwords did not change. You must provide a new password if you wish to enable any additional [asis,subaccount] services.":"De serviceaccount is gekoppeld aan de ’[_1]’ [asis,subaccount] van de gebruiker. De serviceaccountwachtwoorden zijn niet gewijzigd. U moet een nieuw wachtwoord opgeven als u extra [asis,subaccount]-services wilt inschakelen.","The system successfully linked the service account to the “[_1]” user’s [asis,subaccount]. The service account passwords have not changed.":"De serviceaccount is gekoppeld aan de ’[_1]’ [asis,subaccount] van de gebruiker. De serviceaccountwachtwoorden zijn niet gewijzigd.","You cannot edit the account.":"U kunt de account niet bewerken.","Your [asis,cPanel] account exceeds its disk quota. You cannot add or edit users.":"Uw [asis,cPanel]-account overschrijdt het schijfquotum. U kunt geen gebruikers toevoegen of bewerken."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
