//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/user_manager/views/listController.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/user_manager/views/listController-pt_br.js
// Module:    /paper_lantern/user_manager/views/listController-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Do you wish to remove the “[_1]” user from your system?":"Tem certeza de que deseja remover do sistema o usuário “[_1]”?","The service account is invalid.":"A conta de serviço é inválida.","The system successfully linked all of the service accounts for the “[_1]” user to the [asis,subaccount]. The service account passwords did not change.":"O sistema vinculou com êxito todas as contas de serviço do usuário “[_1]” à [asis,subaccount]. As senhas das contas de serviço não mudaram.","The system successfully linked all of the service accounts for the “[_1]” user to the [asis,subaccount]. The service account passwords did not change. You must provide a new password if you wish to enable any additional [asis,subaccount] services.":"O sistema vinculou com êxito todas as contas de serviço do usuário “[_1]” à [asis,subaccount]. As senhas das contas de serviço não mudaram. Você deve fornecer uma nova senha se quiser habilitar quaisquer serviços de [asis,subaccount] adicionais.","The system successfully linked the service account to the “[_1]” user’s [asis,subaccount]. The service account passwords did not change. You must provide a new password if you wish to enable any additional [asis,subaccount] services.":"O sistema vinculou com êxito a conta de serviço à [asis,subaccount] do usuário “[_1]”. As senhas das contas de serviço não mudaram. Você deve fornecer uma nova senha se quiser habilitar quaisquer serviços de [asis,subaccount] adicionais.","The system successfully linked the service account to the “[_1]” user’s [asis,subaccount]. The service account passwords have not changed.":"O sistema vinculou com êxito a conta de serviço à [asis,subaccount] do usuário “[_1]”. As senhas das contas de serviço não mudaram.","You cannot edit the account.":"Você não pode editar a conta.","Your [asis,cPanel] account exceeds its disk quota. You cannot add or edit users.":"Sua conta do [asis,cPanel] excede sua cota de disco. Não é possível adicionar ou editar usuários."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
