//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/views/listEmailAccounts.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/pops/views/listEmailAccounts-de.js
// Module:    /paper_lantern/mail/pops/views/listEmailAccounts-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Account “[_1]” deleted.":"Account “[_1]” deleted.","Changed Quota for “[_1]” to unlimited.":"Changed Quota for “[_1]” to unlimited.","Displaying [_1] to [_2] out of [_3] records":"[_1] bis [_2] von [_3] Datensätzen werden angezeigt.","Password for “[_1]” has been changed.":"Das Kennwort für „[_1]“ wurde geändert.","[numf,_1] messages have been queued for deletion from the outgoing mail queue.":"[numf,_1] messages have been queued for deletion from the outgoing mail queue.","“[_1]”‘s quota is now [format_bytes,_2].":"“[_1]”‘s quota is now [format_bytes,_2]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
