//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple-da.js
// Module:    /paper_lantern/js2/zoneedit/simple-da
// Locale:    da
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX-fejl","Added Record":"Post tilføjet","Adding record …":"Tilføjer post…","Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).":"Adressen kan ikke være en lokal IP-adresse (127.0.0.1 eller 0.0.0.0).","Address must be a fully-qualified domain name.":"Adressen skal være et fuldt kvalificeret domænenavn.","Address must be an IP address.":"Adressen skal være en IP-adresse.","All CNAMEs must be unique.":"Alle CNAME’er skal være entydige.","Deleting record …":"Sletter post…","Error":"Fejl","JSON parse failed.":"JSON-opdeling mislykkedes.","Loading …":"Indlæser…","Name matches an existing CNAME.":"Navnet svarer til et eksisterende CNAME.","Please refresh the page and try again.":"Opdater siden, og prøv igen.","That is not a valid zone name.":"Det er ikke et gyldigt zonenavn.","That name is reserved (already in use).":"Navnet er reserveret (allerede i brug)."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
