//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple-fi.js
// Module:    /paper_lantern/js2/zoneedit/simple-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX-virhe","Added Record":"Tietue lisätty","Adding record …":"Tietuetta lisätään…","Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).":"Osoite ei voi olla paikallinen IP-osoite (127.0.0.1 tai 0.0.0.0).","Address must be a fully-qualified domain name.":"Osoitteen oltava tarkennettu toimialueen nimi","Address must be an IP address.":"Osoitteen on oltava IP-osoite.","All CNAMEs must be unique.":"Kaikkien CNAME-arvojen on oltava yksilöllisiä.","Deleting record …":"Poistetaan tietue…","Error":"Virhe","JSON parse failed.":"JSON-jäsennys epäonnistui.","Loading …":"Ladataan…","Name matches an existing CNAME.":"Nimi vastaa aiemmin luotua CNAME-nimeä.","Please refresh the page and try again.":"Päivitä sivu ja yritä uudelleen.","That is not a valid zone name.":"Tuo ei ole kelvollinen vyöhykkeen nimi.","That name is reserved (already in use).":"Nimi on varattu (on jo käytössä)."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
