//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple-pt.js
// Module:    /paper_lantern/js2/zoneedit/simple-pt
// Locale:    pt
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX Error","Added Record":"Added Record","Adding record …":"Adding record …","Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).":"Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).","Address must be a fully-qualified domain name.":"Address must be a fully-qualified domain name.","Address must be an IP address.":"Address must be an IP address.","All CNAMEs must be unique.":"Todos os CNAMEs deve ser exclusivo.","Deleting record …":"Deleting record …","Error":"Erro","JSON parse failed.":"JSON parse failed.","Loading …":"Carregando …","Name matches an existing CNAME.":"Nome corresponde a um CNAME existente.","Please refresh the page and try again.":"Please refresh the page and try again.","That is not a valid zone name.":"That is not a valid zone name.","That name is reserved (already in use).":"That name is reserved (already in use)."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
