//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple-ru.js
// Module:    /paper_lantern/js2/zoneedit/simple-ru
// Locale:    ru
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"Ошибка AJAX","Added Record":"Добавлена запись","Adding record …":"Добавление записи…","Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).":"Адрес не может быть локальным IP-адресом (127.0.0.1 или 0.0.0.0).","Address must be a fully-qualified domain name.":"Адрес должен быть полным доменным именем.","Address must be an IP address.":"Адрес должен быть IP-адресом.","All CNAMEs must be unique.":"Все значения CNAME должны быть уникальными.","Deleting record …":"Удаление записи…","Error":"Ошибка","JSON parse failed.":"Не удалось выполнить анализ JSON.","Loading …":"Идет загрузка…","Name matches an existing CNAME.":"Имя соответствует существующему значению CNAME.","Please refresh the page and try again.":"Обновите страницу и попробуйте еще раз.","That is not a valid zone name.":"Это недопустимое имя зоны.","That name is reserved (already in use).":"Это имя зарезервировано (уже используется)."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
