//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple-fil.js
// Module:    /paper_lantern/js2/zoneedit/simple-fil
// Locale:    fil
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX Error","Added Record":"Naidagdag ang Record","Adding record …":"Idinaragdag ang record …","Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).":"Ang address ay hindi maaaring isang lokal na IP address (127.0.0.1 o 0.0.0.0).","Address must be a fully-qualified domain name.":"Isang fully-qualified domain name dapat ang address.","Address must be an IP address.":"Isang IP address dapat ang address.","All CNAMEs must be unique.":"Dapat na natatangi ang lahat ng CNAME.","Deleting record …":"Tinatanggal ang record …","Error":"Error","JSON parse failed.":"Nabigo ang pag-parse ng JSON.","Loading …":"Naglo-load …","Name matches an existing CNAME.":"Tumutugma ang pangalan sa umiiral nang CNAME.","Please refresh the page and try again.":"Paki-refresh ang pahina at subukang muli.","That is not a valid zone name.":"Hindi iyan isang wastong pangalan ng zone.","That name is reserved (already in use).":"Nakareserba ang pangalan na iyon (ginagamit na)."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
