//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple-ar.js
// Module:    /paper_lantern/js2/zoneedit/simple-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"خطأ AJAX","Added Record":"السجل الذي تمت إضافته","Adding record …":"جارٍ إضافة سجل…","Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).":"يتعذر أن يكون العنوان أحد عناوين IP المحلية (127.0.0.1 أو 0.0.0.0).","Address must be a fully-qualified domain name.":"يجب أن يكون العنوان اسم مجال مؤهلاً بالكامل.","Address must be an IP address.":"يجب أن يكون العنوان عبارة عن عنوان IP.","All CNAMEs must be unique.":"يجب أن يكون كل CNAME فريدًا.","Deleting record …":"جارٍ حذف السجل…","Error":"خطأ","JSON parse failed.":"فشل توزيع JSON.","Loading …":"جار التحميل‎…","Name matches an existing CNAME.":"الاسم يطابق CNAME الموجود.","Please refresh the page and try again.":"يرجى تحديث الصفحة وإعادة المحاولة.","That is not a valid zone name.":"يعد هذا اسم منطقة غير صالح.","That name is reserved (already in use).":"هذا الاسم محجوز (قيد الاستخدام بالفعل)."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
