//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/zoneedit/simple-de.js
// Module:    /paper_lantern/js2/zoneedit/simple-de
// Locale:    de
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"AJAX-Fehler","Added Record":"Datensatz hinzugefügt","Adding record …":"Datensatz wird hinzugefügt …","Address cannot be a local IP address (127.0.0.1 or 0.0.0.0).":"Die Adresse darf keine lokale IP-Adresse sein (127.0.0.1 oder 0.0.0.0).","Address must be a fully-qualified domain name.":"Die Adresse muss ein vollqualifizierter Domänenname sein","Address must be an IP address.":"Die Adresse muss eine IP-Adresse sein.","All CNAMEs must be unique.":"Alle CNAME-Einträge müssen eindeutig sein.","Deleting record …":"Eintrag wird gelöscht …","Error":"Fehler","JSON parse failed.":"JSON-Parsing fehlgeschlagen.","Loading …":"Ladevorgang läuft …","Name matches an existing CNAME.":"Es ist bereits ein CNAME-Eintrag mit diesem Namen vorhanden.","Please refresh the page and try again.":"Bitte aktualisieren Sie die Seite, und versuchen Sie es noch einmal.","That is not a valid zone name.":"Dies ist kein gültiger Zonenname.","That name is reserved (already in use).":"Dieser Name ist reserviert (wird bereits verwendet)."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
