//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/sql/managehost.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/sql/managehost-fi.js
// Module:    /paper_lantern/js2/sql/managehost-fi
// Locale:    fi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Remote Database Hosts":"Etätietokantapalvelimet","You must enter a valid hostname or [asis,IP] address in the [output,em,Access Host] text box, for example, [asis,example.com] or [asis,169.254.1.1].":"You must enter a valid hostname or [asis,IP] address in the [output,em,Access Host] text box, for example, [asis,example.com] or [asis,169.254.1.1]."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
