//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/greylisting/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/greylisting/index.cmb-ar.js
// Module:    /paper_lantern/mail/greylisting/index.cmb-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,Greylisting] on all domains.":"تم تعطيل [asis,Greylisting] على كل المجالات بنجاح.","Successfully disabled [asis,Greylisting] on “[output,class,_1,nobreak]”.":"تم تعطيل [asis,Greylisting] على “[output,class,_1,nobreak]” بنجاح.","Successfully enabled [asis,Greylisting] on all domains.":"تم تمكين [asis,Greylisting] على كل المجالات بنجاح.","Successfully enabled [asis,Greylisting] on “[output,class,_1,nobreak]”.":"تم تمكين [asis,Greylisting] على “[output,class,_1,nobreak]” بنجاح."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
