//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index-zh_tw.js
// Module:    /paper_lantern/js2/styleswitcher/index-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Applying styles and reloading the page.":"正在套用樣式並重新載入頁面。","Setting default style and reloading the page …":"正在設定預設樣式並重新載入頁面…","[output,strong,Error]: The system failed to apply the style you selected.":"[output,strong,錯誤]: 系統無法套用您選取的樣式。","[output,strong,Error]: The system failed to set the default style.":"[output,strong,錯誤]: 系統無法設定預設樣式。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
