//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index-zh.js
// Module:    /paper_lantern/js2/styleswitcher/index-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Applying styles and reloading the page.":"应用样式和重新加载页面。","Setting default style and reloading the page …":"正在设置默认样式和重新加载页面…","[output,strong,Error]: The system failed to apply the style you selected.":"[output,strong,错误]: 系统无法应用所选样式。","[output,strong,Error]: The system failed to set the default style.":"[output,strong,错误]: 系统无法设置默认样式。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
