//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index-it.js
// Module:    /paper_lantern/js2/styleswitcher/index-it
// Locale:    it
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Applying styles and reloading the page.":"Applicazione degli stili e ricaricamento della pagina.","Setting default style and reloading the page …":"Impostazione stile predefinito e ricaricamento pagina in corso…","[output,strong,Error]: The system failed to apply the style you selected.":"[output,strong,Errore]: il sistema non è riuscito ad applicare lo stile selezionato.","[output,strong,Error]: The system failed to set the default style.":"[output,strong,Errore]: il sistema non è riuscito a impostare lo stile predefinito."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
