//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index-cs.js
// Module:    /paper_lantern/js2/styleswitcher/index-cs
// Locale:    cs
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Applying styles and reloading the page.":"Probíhá použití stylů a nové načtení stránky.","Setting default style and reloading the page …":"Nastavení výchozího stylu a nové načtení stránky…","[output,strong,Error]: The system failed to apply the style you selected.":"[output,strong,Chyba]: Systému se nepodařilo aplikovat zvolený styl.","[output,strong,Error]: The system failed to set the default style.":"[output,strong,Chyba]: Systému se nepodařilo nastavit výchozí styl."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
