//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index-he.js
// Module:    /paper_lantern/js2/styleswitcher/index-he
// Locale:    he
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Applying styles and reloading the page.":"המערכת מחילה סגנונות וטוענת מחדש את הדף.","Setting default style and reloading the page …":"המערכת מגדירה סגנון ברירת מחדל וטוענת מחדש את הדף…","[output,strong,Error]: The system failed to apply the style you selected.":"[output,strong,שגיאה]: המערכת לא הצליחה להחיל את הסגנון שבחרת.","[output,strong,Error]: The system failed to set the default style.":"[output,strong,שגיאה]: המערכת לא הצליחה להגדיר את סגנון ברירת המחדל."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
