//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index-fr.js
// Module:    /paper_lantern/js2/styleswitcher/index-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Applying styles and reloading the page.":"Application des styles et rechargement de la page.","Setting default style and reloading the page …":"Définition du style par défaut et rechargement de la page…","[output,strong,Error]: The system failed to apply the style you selected.":"[output,strong,Erreur] : le système n’a pas pu appliquer le style sélectionné.","[output,strong,Error]: The system failed to set the default style.":"[output,strong,Erreur] : le système n’a pas pu définir le style par défaut."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
