//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/styleswitcher/index-vi.js
// Module:    /paper_lantern/js2/styleswitcher/index-vi
// Locale:    vi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Applying styles and reloading the page.":"Đang áp dụng kiểu và tải lại trang.","Setting default style and reloading the page …":"Đang đặt kiểu mặc định và tải lại trang …","[output,strong,Error]: The system failed to apply the style you selected.":"[output,strong,Lỗi]: Hệ thống không áp dụng được kiểu bạn chọn.","[output,strong,Error]: The system failed to set the default style.":"[output,strong,Lỗi]: Hệ thống không đặt được kiểu mặc định."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
