//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/domains/index.cmb.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/domains/index.cmb-th.js
// Module:    /paper_lantern/domains/index.cmb-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Addon":"Addon","Alias":"Alias","Create a New Domain":"Create a New Domain","Displaying [numf,_1] through [numf,_2] out of [quant,_3,item,items]":"Displaying [numf,_1] through [numf,_2] out of [quant,_3,item,items]","List Domains":"List Domains","Manage the Domain":"Manage the Domain","Subdomain":"โดเมนย่อย","The server reserves this subdomain for system use only. Enter a different subdomain.":"The server reserves this subdomain for system use only. Enter a different subdomain.","This domain already exists on this account.":"This domain already exists on this account.","You must enter a valid subdomain.":"You must enter a valid subdomain."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
