//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/domain_selection.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/domain_selection-ja.js
// Module:    /paper_lantern/zone_editor/views/domain_selection-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add a [asis,CNAME] Record":"[asis,CNAME] レコードの追加","Add a [asis,CNAME] Record for “[_1]”":"Add a [asis,CNAME] Record for “[_1]”","Add an [asis,A] Record":"[asis,A] レコードの追加","Add an [asis,A] Record for “[_1]”":"Add an [asis,A] Record for “[_1]”","Add an [asis,MX] Record":"Add an [asis,MX] Record","Add an [asis,MX] Record for “[_1]”":"Add an [asis,MX] Record for “[_1]”","Address":"アドレス","Cancel":"キャンセル","Destination":"保存先","Fully qualified domain name":"Fully qualified domain name","Integer":"整数","Name":"名前","Priority":"優先順位","This field is required.":"このフィールドは必須です。","You successfully added the [asis,_1] record for “[_2]”.":"You successfully added the [asis,_1] record for “[_2]”.","You successfully added the following [asis,_1] record for “[_2]”: [_3]":"You successfully added the following [asis,_1] record for “[_2]”: [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
