//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/domain_selection.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/domain_selection-ko.js
// Module:    /paper_lantern/zone_editor/views/domain_selection-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add a [asis,CNAME] Record":"[asis,CNAME] 레코드 추가","Add a [asis,CNAME] Record for “[_1]”":"Add a [asis,CNAME] Record for “[_1]”","Add an [asis,A] Record":"[asis,A] 레코드 추가","Add an [asis,A] Record for “[_1]”":"Add an [asis,A] Record for “[_1]”","Add an [asis,MX] Record":"Add an [asis,MX] Record","Add an [asis,MX] Record for “[_1]”":"Add an [asis,MX] Record for “[_1]”","Address":"주소","Cancel":"취소","Destination":"대상","Fully qualified domain name":"Fully qualified domain name","Integer":"정수","Name":"이름","Priority":"우선 순위","This field is required.":"이 필드는 반드시 입력해야 합니다.","You successfully added the [asis,_1] record for “[_2]”.":"You successfully added the [asis,_1] record for “[_2]”.","You successfully added the following [asis,_1] record for “[_2]”: [_3]":"You successfully added the following [asis,_1] record for “[_2]”: [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
