//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/domain_selection.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/domain_selection-th.js
// Module:    /paper_lantern/zone_editor/views/domain_selection-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Add a [asis,CNAME] Record":"เพิ่มระเบียน [asis,CNAME]","Add a [asis,CNAME] Record for “[_1]”":"Add a [asis,CNAME] Record for “[_1]”","Add an [asis,A] Record":"เพิ่มระเบียน [asis,A]","Add an [asis,A] Record for “[_1]”":"Add an [asis,A] Record for “[_1]”","Add an [asis,MX] Record":"Add an [asis,MX] Record","Add an [asis,MX] Record for “[_1]”":"Add an [asis,MX] Record for “[_1]”","Address":"ที่อยู่","Cancel":"ยกเลิก","Destination":"ปลายทาง","Fully qualified domain name":"Fully qualified domain name","Integer":"จำนวนเต็ม","Name":"ชื่อ","Priority":"ลำดับความสำคัญ","This field is required.":"จำเป็นต้องมีเขตข้อมูลนี้","You successfully added the [asis,_1] record for “[_2]”.":"You successfully added the [asis,_1] record for “[_2]”.","You successfully added the following [asis,_1] record for “[_2]”: [_3]":"You successfully added the following [asis,_1] record for “[_2]”: [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
