//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/manage.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/views/manage-no.js
// Module:    /paper_lantern/zone_editor/views/manage-no
// Locale:    no
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Certificate Authority":"Certificate Authority","Mail Address for Notifications":"Mail Address for Notifications","The certificate authority’s domain name.":"The certificate authority’s domain name.","The location to which the certificate authority will report exceptions. Either a [asis,mailto] or standard [asis,URL].":"The location to which the certificate authority will report exceptions. Either a [asis,mailto] or standard [asis,URL].","You successfully added the [asis,_1] record for “[_2]”.":"You successfully added the [asis,_1] record for “[_2]”.","You successfully added the following [asis,_1] record for “[_2]”: [_3]":"You successfully added the following [asis,_1] record for “[_2]”: [_3]","You successfully deleted the [asis,_1] record.":"You successfully deleted the [asis,_1] record.","You successfully deleted the [asis,_1] record: [_2]":"You successfully deleted the [asis,_1] record: [_2]","You successfully reset the zone for “[_1]”.":"You successfully reset the zone for “[_1]”.","You successfully updated the [asis,_1] record for “[_2]”.":"You successfully updated the [asis,_1] record for “[_2]”.","You successfully updated the following [asis,_1] record for “[_2]”: [_3]":"You successfully updated the following [asis,_1] record for “[_2]”: [_3]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
