//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/boxtrapper/conf.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/boxtrapper/conf-ar.js
// Module:    /paper_lantern/mail/boxtrapper/conf-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Minimum [asis,Apache] [asis,SpamAssassin] Spam Score required to bypass [asis,BoxTrapper]:":"الحد الأدنى من [asis,Apache] [asis,SpamAssassin] المطلوب من نقاط البريد المزعج [asis,BoxTrapper]:","The minimum spam score must be numeric.":"يجب أن الحد الأدنى لنقاط البريد المزعج‬ رقميًا:","The number of days that you wish to keep logs and messages in the queue.":"عدد الأيام التي ترغب في الاحتفاظ فيها بالسجلات والرسائل في قائمة الانتظار.","The number of days to keep logs must be a positive integer.":"يجب أن يكون عدد أيام حفظ السجلات عددًا صحيحًا."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
