//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/boxtrapper/conf.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/boxtrapper/conf-zh.js
// Module:    /paper_lantern/mail/boxtrapper/conf-zh
// Locale:    zh
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Minimum [asis,Apache] [asis,SpamAssassin] Spam Score required to bypass [asis,BoxTrapper]:":"要绕开 [asis,BoxTrapper]，需要 [asis,Apache] [asis,SpamAssassin] 垃圾邮件得分至少为:","The minimum spam score must be numeric.":"最低垃圾邮件得分必须为数字。","The number of days that you wish to keep logs and messages in the queue.":"您希望日志和消息在队列中保留的天数。","The number of days to keep logs must be a positive integer.":"保留日志的天数必须为正整数。"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
