//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/boxtrapper/conf.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/boxtrapper/conf-fr.js
// Module:    /paper_lantern/mail/boxtrapper/conf-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Minimum [asis,Apache] [asis,SpamAssassin] Spam Score required to bypass [asis,BoxTrapper]:":"Score [asis,Apache] [asis,SpamAssassin] spam minimum requis pour contourner [asis,BoxTrapper] :","The minimum spam score must be numeric.":"Le score spam minimum doit être une valeur numérique.","The number of days that you wish to keep logs and messages in the queue.":"Durée de conservation des journaux et des messages en file d’attente en jours.","The number of days to keep logs must be a positive integer.":"La durée de conservation des journaux (en jours) doit être un nombre entier positif."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
