//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/webdav/accounts_webdav.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/webdav/accounts_webdav-zh_tw.js
// Module:    /paper_lantern/js2/webdav/accounts_webdav-zh_tw
// Locale:    zh_tw
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Cancel":"取消","Change":"變更","Click to disable Digest Authentication.":"按一下以停用摘要式驗證。","Click to enable Digest Authentication.":"按一下以啟用摘要式驗證。","Close":"關閉","Directory":"目錄","Directory Path":"目錄路徑","Directory paths cannot be empty or contain the following characters: [output,chr,92] ? % * : | [output,quot] [output,gt] [output,lt]":"目錄路徑不能是空白的或包含以下字元: [output,chr,92] ? % * : | [output,quot] [output,gt] [output,lt]","Disable Digest Authentication":"停用摘要式驗證","Disabling Digest Authentication on account “[_1]” …":"正在停用帳戶 “[_1]” 的摘要式驗證…","Domain":"網域","Enable Digest Authentication":"啟用摘要式驗證","Enabling Digest Authentication on account “[_1]” …":"正在啟用帳戶“[_1]”的摘要式驗證…","Home Directory Updated":"已更新主目錄","Notice":"通知","OK":"確定","Please try again.":"請再試一次。","Set Read-Only":"設定唯讀","Set Read-Write":"設定讀寫","Setting Read-Only Access":"正在設定唯讀存取權限","Setting Read-Only Access on account “[_1]” …":"正在設定帳戶“[_1]”的唯讀存取權限…","Setting Read-Write Access":"正在設定讀寫存取權限","Setting Read-Write Access on account “[_1]” …":"正在設定帳戶“[_1]”的讀寫存取權限…","Success!":"成功!","The [asis,WebDisk] username cannot exceed [numf,_1] characters.":"The [asis,WebDisk] username cannot exceed [numf,_1] characters.","The [asis,WebDisk] username cannot start with a period, end with a period, or include two consecutive periods.":"The [asis,WebDisk] username cannot start with a period, end with a period, or include two consecutive periods.","The [asis,WebDisk] username name and domain cannot exceed [numf,_1] characters.":"The [asis,WebDisk] username name and domain cannot exceed [numf,_1] characters.","Updating Home Directory":"正在更新主目錄","Webdav Login":"Webdav 登入","You can only enter letters, numbers, periods, hyphens, and underscores.":"You can only enter letters, numbers, periods, hyphens, and underscores.","You must enter a [asis,WebDisk] username.":"You must enter a [asis,WebDisk] username."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
