//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/file_and_directory_restoration/services/backupAPI.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/file_and_directory_restoration/services/backupAPI-vi.js
// Module:    /paper_lantern/file_and_directory_restoration/services/backupAPI-vi
// Locale:    vi
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Compressed":"Đã Nén","Incremental":"Tăng dần","Uncompressed":"Không Nén"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
