//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/mail/greylisting/views/domains.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/mail/greylisting/views/domains-pt.js
// Module:    /paper_lantern/mail/greylisting/views/domains-pt
// Locale:    pt
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Successfully disabled [asis,Greylisting] on all domains.":"Successfully disabled [asis,Greylisting] on all domains.","Successfully disabled [asis,Greylisting] on “[output,class,_1,nobreak]”.":"Successfully disabled [asis,Greylisting] on “[output,class,_1,nobreak]”.","Successfully enabled [asis,Greylisting] on all domains.":"Successfully enabled [asis,Greylisting] on all domains.","Successfully enabled [asis,Greylisting] on “[output,class,_1,nobreak]”.":"Successfully enabled [asis,Greylisting] on “[output,class,_1,nobreak]”."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
