//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/filemanager/editors/html_editor.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/filemanager/editors/html_editor-ko.js
// Module:    /paper_lantern/filemanager/editors/html_editor-ko
// Locale:    ko
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Failed to saving the file with the following errors: [_1]":"다음 오류가 발생하여 파일을 저장하지 못했습니다. [_1]","Failed to saving the file.":"파일을 저장하지 못했습니다.","Successfully saved the file.":"파일이 저장되었습니다.","Successfully saved the file: [_1]":"파일이 저장되었습니다. [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
