//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/filemanager/editors/html_editor.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/filemanager/editors/html_editor-th.js
// Module:    /paper_lantern/filemanager/editors/html_editor-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Failed to saving the file with the following errors: [_1]":"ไม่สามารถบันทึกไฟล์โดยมีข้อผิดพลาดต่อไปนี้: [_1]","Failed to saving the file.":"ไม่สามารถบันทึกไฟล์ได้","Successfully saved the file.":"บันทึกไฟล์เสร็จสมบูรณ์แล้ว","Successfully saved the file: [_1]":"บันทึกไฟล์เสร็จสมบูรณ์แล้ว: [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
