//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/filemanager/editors/html_editor.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/filemanager/editors/html_editor-ja.js
// Module:    /paper_lantern/filemanager/editors/html_editor-ja
// Locale:    ja
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Failed to saving the file with the following errors: [_1]":"次のエラーのため、ファイルを保存できませんでした: [_1]","Failed to saving the file.":"ファイルを保存できませんでした。","Successfully saved the file.":"ファイルが正常に保存されました。","Successfully saved the file: [_1]":"ファイルが正常に保存されました: [_1]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
