//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/models/dynamic_table.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/models/dynamic_table-pt_br.js
// Module:    /paper_lantern/zone_editor/models/dynamic_table-pt_br
// Locale:    pt_br
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Displaying [numf,_1] to [numf,_2] out of [quant,_3,item,items]":"Exibindo [numf,_1] a [numf,_2] de [quant,_3,item,itens]"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
