//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/email_accounts/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/email_accounts/index-ar.js
// Module:    /paper_lantern/email_accounts/index-ar
// Locale:    ar
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"Create an Email Account":"Create an Email Account","List Email Accounts":"List Email Accounts","Manage Default Email Account":"Manage Default Email Account","Manage an Email Account":"Manage an Email Account"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
