//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/cron/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/cron/index-es_es.js
// Module:    /paper_lantern/js2/cron/index-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"Error de AJAX","Error":"Error","JSON parse failed.":"Error de análisis de JSON.","Loading …":"Cargando…","Please refresh the page and try again.":"Actualice la página e inténtelo de nuevo.","less »":"menos »"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
