//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/cron/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/cron/index-fr.js
// Module:    /paper_lantern/js2/cron/index-fr
// Locale:    fr
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"Erreur AJAX","Error":"Erreur","JSON parse failed.":"L’analyse JSON a échoué.","Loading …":"Chargement…","Please refresh the page and try again.":"Actualisez la page et réessayez.","less »":"moins »"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
