//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/js2/cron/index.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/js2/cron/index-th.js
// Module:    /paper_lantern/js2/cron/index-th
// Locale:    th
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"AJAX Error":"ข้อผิดพลาด AJAX","Error":"ข้อผิดพลาด","JSON parse failed.":"การแยกวิเคราะห์ JSON ล้มเหลว","Loading …":"กำลังโหลด …","Please refresh the page and try again.":"โปรดรีเฟรชหน้าและลองอีกครั้ง","less »":"น้อยกว่า »"};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
