//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/services/domains.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/services/domains-es_es.js
// Module:    /paper_lantern/zone_editor/services/domains-es_es
// Locale:    es_es
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The API request failed with the following error: [_1] - [_2].":"La solicitud de la API ha generado el siguiente error: [_1] - [_2].","Your session may have expired or you logged out of the system. [output,url,_1,Login] again to continue.":"Es posible que la sesión haya caducado o que haya salido del sistema. [output,url,_1,Inicie sesión] de nuevo para continuar."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
