//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/services/zones.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/services/zones-pl.js
// Module:    /paper_lantern/zone_editor/services/zones-pl
// Locale:    pl
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The API request failed with the following error: [_1] - [_2].":"Nie można wykonać żądania wysłanego do interfejsu API z powodu następującego błędu: [_1]–[_2].","Your session may have expired or you logged out of the system. [output,url,_1,Login] again to continue.":"Twoja sesja mogła wygasnąć lub nastąpiło Twoje wylogowanie z systemu. Aby kontynuować, [output,url,_1,zaloguj się] ponownie."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
