//~~GENERATED~~
//-------------------------------------------------------------
// Source:    /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/services/zones.js
// Generated: /usr/local/cpanel/base/frontend/paper_lantern/zone_editor/services/zones-el.js
// Module:    /paper_lantern/zone_editor/services/zones-el
// Locale:    el
// This file is generated by the cpanel localization system
// using the bin/_build_translated_js_hash_files.pl script.
//-------------------------------------------------------------
// !!! Do not hand edit this file !!!
//-------------------------------------------------------------
(function() {
    // The raw lexicon.
    var newLex = {"The API request failed with the following error: [_1] - [_2].":"Το αίτημα API απέτυχε με το εξής σφάλμα: [_1] - [_2].","Your session may have expired or you logged out of the system. [output,url,_1,Login] again to continue.":"Η περίοδος λειτουργίας σας ενδέχεται να έχει λήξει ή έχετε αποσυνδεθεί από το σύστημα. [output,url,_1,Συνδεθείτε] εκ νέου για να συνεχίσετε."};

    if (!this.LEXICON) {
        this.LEXICON = {};
    }

    for(var item in newLex) {
        if(newLex.hasOwnProperty(item)) {
            var value = newLex[item];
            if (typeof(value) === "string" && value !== "") {
                // Only add it if there is a value.
                this.LEXICON[item] = value;
            }
        }
    }
})();
//~~END-GENERATED~~
